# Generated by Django 4.2.1 on 2023-05-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='firtname_name',
            new_name='first_name',
        ),
    ]
