# Generated by Django 4.2.1 on 2023-06-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_students', '0002_rename_firtname_name_studentmodel_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to='students/profile/'),
        ),
    ]
